name: CI_for_version_tag

on:
  pull_request:
    branches: 
      - feature/add_action
    types: [closed]

jobs:
  update_version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - name: Creation tag
        run: |
          git fetch --tags
          latest_tag_name=$(git tag -l --sort=-v:refname | head -n 1)
          num_0=$(echo $latest_tag_name | sed 's:\.[0-9]*\.[0-9]*::')
          num_1=$(echo $latest_tag_name | sed 's:^v[0-9]*\.::' | sed 's:\.[0-9]*::')
          num_2=$(echo $latest_tag_name | sed 's:^v[0-9]*\.[0-9]*\.::')
          num_2=$(expr $num_2 + 1)
          new_tag_name="test_${num_0}.${num_1}.${num_2}" 
          git config --global user.email "onoda.ryo@genetec.co.jp"
          git config --global user.name "ryoonoda"
          git tag -a $new_tag_name -m "attach ${new_tag_name} tag"
          git push origin $new_tag_name
          
      - name: Creation release note
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.creation_tag.outputs.new_tag_name }}
          release_name: Release ${{ steps.creation_tag.outputs.new_tag_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      
